library:
  log:
    format: text
    level: info
    caller: false

genCode:
  upstream:
    contextTimeout: 120s
    http:
      basePath: /
      readTimeout: 120s
      writeTimeout: 120s
      common:
        hostName: ""
        port: 6060
  downstream:
    contextTimeout: 120s
    github:
      serviceURL: https://api.github.com
      clientTimeout: 59s
